"""
Character data model
"""
from dataclasses import dataclass, field
from typing import Optional, List

@dataclass
class CharacterAppearance:
    """Stage 1: Basic appearance for image generation"""
    species: str = ""
    sex_gender: str = ""
    age: str = ""
    physical_shape: str = ""
    hair_details: str = ""
    eye_details: str = ""
    main_colors: str = ""
    clothing: str = ""
    artstyle: str = ""
    
    def to_prompt_string(self) -> str:
        """Convert appearance to string for prompt generation"""
        fields_dict = {
            "Species": self.species,
            "Sex/Gender": self.sex_gender,
            "Age": self.age,
            "Physical Shape": self.physical_shape,
            "Hair Details": self.hair_details,
            "Eye Details": self.eye_details,
            "Main Colors": self.main_colors,
            "Clothing": self.clothing,
            "Artstyle": self.artstyle
        }
        return '\n'.join([f"{k}: {v}" for k, v in fields_dict.items() if v.strip()])


@dataclass
class CharacterPersonality:
    """Stage 2: Extended personality and background"""
    deformation_mark: str = ""
    skills_powers: str = ""
    context_universe: str = ""
    social_context: str = ""
    occupation: str = ""
    ethnicity: str = ""
    personality_traits: str = ""
    extras: str = ""
    backstory: str = ""  # Generated by AI, editable by user
    
    def to_prompt_string(self) -> str:
        """Convert personality to string for prompt enhancement"""
        fields_dict = {
            "Deformation/Mark": self.deformation_mark,
            "Skills/Powers": self.skills_powers,
            "Context/Universe": self.context_universe,
            "Social/Context": self.social_context,
            "Occupation/Profession": self.occupation,
            "Ethnicity": self.ethnicity,
            "Personality Traits": self.personality_traits,
            "Extras": self.extras
        }
        return '\n'.join([f"{k}: {v}" for k, v in fields_dict.items() if v.strip()])


@dataclass
class Character:
    """Complete character data"""
    appearance: CharacterAppearance = field(default_factory=CharacterAppearance)
    personality: CharacterPersonality = field(default_factory=CharacterPersonality)
    
    # Generated content
    name: str = ""
    image_prompts: List[str] = field(default_factory=list)
    images_base64: List[str] = field(default_factory=list)
    
    def get_full_description(self) -> str:
        """Get complete character description for agent context"""
        return f"""
Character Name: {self.name}

APPEARANCE:
{self.appearance.to_prompt_string()}

PERSONALITY & BACKGROUND:
{self.personality.to_prompt_string()}

BACKSTORY:
{self.personality.backstory}
"""
    
    def is_appearance_complete(self) -> bool:
        """Check if minimum appearance fields are filled"""
        return bool(self.appearance.species or self.appearance.sex_gender or 
                   self.appearance.physical_shape or self.appearance.hair_details)